source/BancoConcursos/WebBConcursos/Controllers/BancasController.cs
using Dominio;
using Infra.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBConcursos.Models;

namespace WebBConcursos.Controllers
{
    [Authorize]
    public class BancasController : Controller
    {
        private readonly Repository repository;
        public BancasController(Repository Repository)
        {
            this.repository = Repository;
        }
        public ActionResult Index()
        {
            return View(PreencheModel());
        }

        private BancaViewModel PreencheModel()
        {
            int total = 0;
            IEnumerable<BancaExaminadora> bancas = this.repository.BancaExaminadoraRepository.GetAll(x => x.Nome, 10, 1, out total);
            return new BancaViewModel(bancas);
        }

        public ActionResult Listar()
        {
            return PartialView("_listar", PreencheModel());
        }

        public ActionResult Excluir(int id)
        {
            BancaExaminadora banca = this.repository.BancaExaminadoraRepository.GetById(id);
            if (banca != null)
            {
                BancaModel model = new BancaModel(banca);
                return PartialView("_excluir", model);
            }
            return PartialView("_excluir", null);
        }

        [HttpPost]
        public ActionResult ExcluirFinal(int id)
        {
            if (ModelState.IsValid)
            {
                BancaExaminadora banca = this.repository.BancaExaminadoraRepository.GetById(id);
                if (banca != null)
                {
                    this.repository.BancaExaminadoraRepository.Delete(banca);
                    this.repository.Save();
                }
                return View("_listar", PreencheModel());
            }
            else
            {
                return Json(new { Msg = "Preencha todos os campos!", Erro = true });
            }
        }

        public ActionResult Editar(int? id)
        {
            if (id.HasValue)
            {
                BancaExaminadora banca = this.repository.BancaExaminadoraRepository.GetById(id.Value);
                if (banca != null)
                {
                    BancaModel model = new BancaModel(banca);
                    return PartialView("_editar", model);
                }
            }
            return PartialView("_editar", null);
        }

        [HttpPost]
        public ActionResult Editar(BancaModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.BancaId.HasValue)
                {
                    BancaExaminadora banca = this.repository.BancaExaminadoraRepository.GetById(model.BancaId.Value);
                    if (banca != null)
                    {
                        banca.Alterar(model.Nome, model.Sigla, model.Tags);
                        this.repository.BancaExaminadoraRepository.Update(banca);
                        this.repository.Save();
                    }
                }
                else
                {
                    BancaExaminadora banca = new BancaExaminadora(model.Nome, model.Sigla, model.Tags);
                    this.repository.BancaExaminadoraRepository.Add(banca);
                    this.repository.Save();
                }

                return View("_listar", PreencheModel());
            }
            else
            {
                return Json(new { Msg = "Preencha todos os campos!", Erro = true });
            }
        }

	}
}

source/BancoConcursos/WebBConcursos/Views/Bancas/Index.cshtml
@{
    ViewBag.Title = "Admin - Bancas Examinadoras";
}

<div class="row">
    <div class="col-md-12">
        <h2>Bancas Examinadoras</h2>
    </div><!--/col-md-12-->
</div><!--/row-->

<div class="row">
    <div class="col-md-12">
        <div class="block-web">
            <div class="header">
                <div class="actions"> <a class="minimize" href="#"><i class="fa fa-chevron-down"></i></a> <a class="refresh" href="#"><i class="fa fa-repeat"></i></a> <a class="close-down" href="#"><i class="fa fa-times"></i></a> </div>
                <h3 class="content-header">&nbsp;</h3>
            </div>
            <div class="porlets-content">
                <div class="adv-table editable-table ">
                    <div class="clearfix">
                        <div class="btn-group">
                            <button class="btn btn-primary novo-registro" data-entity="@ViewContext.RouteData.Values["Controller"]">
                                Novo <i class="fa fa-plus"></i>
                            </button>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">
                                Ferramentas <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Imprimir</a></li>
                                <li><a href="#">Salvar como PDF</a></li>
                                <li><a href="#">Exportar par Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="margin-top-10"></div>
                    <div id="div-listagem">
                        @Html.Action("Listar")
                    </div>
                </div>

            </div><!--/porlets-content-->
        </div><!--/block-web-->
    </div><!--/col-md-12-->
</div><!--/row-->

<div id="modal-result">
</div>

source/BancoConcursos/WebBConcursos/Views/Bancas/_editar.cshtml
@model WebBConcursos.Models.BancaModel
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="modal-registro">
    @using (Ajax.BeginForm("Editar", "Bancas", new AjaxOptions { UpdateTargetId = "div-listagem", OnComplete = "Completo", OnFailure = "Falha", OnBegin = "Carregando", InsertionMode = InsertionMode.Replace }, new { @class = "form-horizontal", @style = "margin-bottom: 0px !important;" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(h => h.BancaId)
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                    <h4 id="myModalLabel" class="modal-title">Editar Banca Examinadora</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)
                        <div class="form-group w-v">
                            @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Nome)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Sigla, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Sigla, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Tags, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Tags, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cancelar</button>
                    <button class="btn btn-primary" type="submit">Salvar</button>
                </div>
            </div>
        </div>
    }
</div>
<script type="text/javascript">
    function ReparseValidation() {
        $.validator.unobtrusive.parse("#modal-registro");
    }
    ReparseValidation();
</script>

source/BancoConcursos/WebBConcursos/Views/Bancas/_excluir.cshtml
@model WebBConcursos.Models.BancaModel
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="modal-delete">
    @using (Ajax.BeginForm("ExcluirFinal", "Bancas", new AjaxOptions { UpdateTargetId = "div-listagem", OnComplete = "Completo", OnFailure = "Falha", OnBegin = "Carregando", InsertionMode = InsertionMode.Replace }, new { @class = "form-horizontal", @style = "margin-bottom: 0px !important;" }))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" id="id" value="@Model.BancaId" />
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                    <h4 id="myModalLabel" class="modal-title">Excluir Banca Examinadora</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        Deseja realmente excluir o registro abaixo?
                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.DisplayTextFor(model => model.Nome)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cancelar</button>
                    <button class="btn btn-danger" type="submit">Excluir</button>
                </div>
            </div>
        </div>
    }
</div>

source/BancoConcursos/WebBConcursos/Views/Bancas/_listar.cshtml
@model WebBConcursos.Models.BancaViewModel
@{
    Layout = null;
}
<table class="table table-striped table-hover table-bordered" id="editable-sample">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>Sigla</th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Bancas)
        {
            <tr class="">
                <td>@item.BancaId</td>
                <td>@item.Nome</td>
                <td>@item.Sigla</td>
                <td><a class="editar-registro" href="javascript:EditarRegistro(@item.BancaId, '@ViewContext.RouteData.Values["Controller"]');"><img src="@Url.Content("~/Content/images/edit.png")" border="0" /></a></td>
                <td><a class="excluir-registro" href="javascript:ExcluirRegistro(@item.BancaId, '@ViewContext.RouteData.Values["Controller"]');"><img src="@Url.Content("~/Content/images/del.png")" border="0" /></a></td>
            </tr>
        }
    </tbody>
</table>