source/BancoConcursos/WebBConcursos/Controllers/AreasController.cs
using Dominio;
using Infra.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBConcursos.Models;

namespace WebBConcursos.Controllers
{
    [Authorize]
    public class AreasController : Controller
    {
        private readonly Repository repository;
        public AreasController(Repository Repository)
        {
            this.repository = Repository;
        }

        public ActionResult Index()
        {
            return View(PreencheModel());
        }

        private AreaViewModel PreencheModel()
        {
            int total = 0;
            IEnumerable<Area> areas = this.repository.AreaRepository.GetAll(x => x.Nome, 10, 1, out total);
            return new AreaViewModel(areas);
        }

        public ActionResult Listar()
        {
            return PartialView("_listar", PreencheModel());
        }

        public ActionResult Excluir(int id)
        {
            Area area = this.repository.AreaRepository.GetById(id);
            if (area != null)
            {
                AreaModel model = new AreaModel(area);
                return PartialView("_excluir", model);
            }
            return PartialView("_excluir", null);
        }

        [HttpPost]
        public ActionResult ExcluirFinal(int id)
        {
            if (ModelState.IsValid)
            {
                Area area = this.repository.AreaRepository.GetById(id);
                if (area != null)
                {
                    this.repository.AreaRepository.Delete(area);
                    this.repository.Save();
                }
                return View("_listagem", PreencheModel());
            }
            else
            {
                return Json(new { Msg = "Preencha todos os campos!", Erro = true });
            }
        }

        public ActionResult Editar(int? id)
        {
            if (id.HasValue)
            {
                Area area = this.repository.AreaRepository.GetById(id.Value);
                if (area != null)
                {
                    AreaModel model = new AreaModel(area);
                    return PartialView("_editar", model);
                }
            }
            return PartialView("_editar", null);
        }

        [HttpPost]
        public ActionResult Editar(AreaModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.AreaId.HasValue)
                {
                    Area area = this.repository.AreaRepository.GetById(model.AreaId.Value);
                    if (area != null)
                    {
                        area.Alterar(model.Nome);
                        this.repository.AreaRepository.Update(area);
                        this.repository.Save();
                    }
                }
                else
                {
                    Area area = new Area(model.Nome);
                    this.repository.AreaRepository.Add(area);
                    this.repository.Save();
                }

                return View("_listar", PreencheModel());
            }
            else
            {
                return Json(new { Msg = "Preencha todos os campos!", Erro = true });
            }
        }
	}
}

source/BancoConcursos/WebBConcursos/Views/Areas/Index.cshtml
@{
    ViewBag.Title = "Admin - Áreas";
}

<div class="row">
    <div class="col-md-12">
        <h2>Áreas</h2>
    </div><!--/col-md-12-->
</div><!--/row-->

<div class="row">
    <div class="col-md-12">
        <div class="block-web">
            <div class="header">
                <div class="actions"> <a class="minimize" href="#"><i class="fa fa-chevron-down"></i></a> <a class="refresh" href="#"><i class="fa fa-repeat"></i></a> <a class="close-down" href="#"><i class="fa fa-times"></i></a> </div>
                <h3 class="content-header">&nbsp;</h3>
            </div>
            <div class="porlets-content">
                <div class="adv-table editable-table ">
                    <div class="clearfix">
                        <div class="btn-group">
                            <button class="btn btn-primary novo-registro" data-entity="@ViewContext.RouteData.Values["Controller"]">
                                Novo <i class="fa fa-plus"></i>
                            </button>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">
                                Ferramentas <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Imprimir</a></li>
                                <li><a href="#">Salvar como PDF</a></li>
                                <li><a href="#">Exportar par Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="margin-top-10"></div>
                    <div id="div-listagem">
                        @Html.Action("Listar")
                    </div>
                </div>

            </div><!--/porlets-content-->
        </div><!--/block-web-->
    </div><!--/col-md-12-->
</div><!--/row-->

<div id="modal-result">
</div>

source/BancoConcursos/WebBConcursos/Views/Areas/_editar.cshtml
@model WebBConcursos.Models.AreaModel
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="modal-registro">
@using (Ajax.BeginForm("Editar", "Areas", new AjaxOptions { UpdateTargetId = "div-listagem", OnComplete = "Completo", OnFailure = "Falha", OnBegin = "Carregando", InsertionMode = InsertionMode.Replace }, new { @class = "form-horizontal", @style = "margin-bottom: 0px !important;" }))
    {
    @Html.AntiForgeryToken()
    @Html.HiddenFor(h => h.AreaId)

    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                <h4 id="myModalLabel" class="modal-title">Editar Área</h4>
            </div>
            <div class="modal-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
                            <div class="col-md-10 w-v">
                                @Html.TextBoxFor(model => model.Nome, new { @class = "form-control focus" })
                                @Html.ValidationMessageFor(model => model.Nome)
                            </div>
                        </div>
                    </div>
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button" id="btnClose">Cancelar</button>
                <button class="btn btn-primary" type="submit">Salvar</button>
            </div>
        </div>
    </div>
}
</div>
<script type="text/javascript">
    function ReparseValidation() {
        $.validator.unobtrusive.parse("#modal-registro");
    }
    ReparseValidation();
</script>

source/BancoConcursos/WebBConcursos/Views/Areas/_excluir.cshtml
@model WebBConcursos.Models.AreaModel
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="modal-delete">
    @using (Ajax.BeginForm("ExcluirFinal", "Areas", new AjaxOptions { UpdateTargetId = "div-listagem", OnComplete = "Completo", OnFailure = "Falha", OnBegin = "Carregando", InsertionMode = InsertionMode.Replace }, new { @class = "form-horizontal", @style = "margin-bottom: 0px !important;" }))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" id="id" value="@Model.AreaId" />
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                    <h4 id="myModalLabel" class="modal-title">Excluir Área</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        Deseja realmente excluir o registro abaixo?
                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.DisplayTextFor(model => model.Nome)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cancelar</button>
                    <button class="btn btn-danger" type="submit">Excluir</button>
                </div>
            </div>
        </div>
    }
</div>

source/BancoConcursos/WebBConcursos/Views/Areas/_listar.cshtml
@model WebBConcursos.Models.AreaViewModel
@{
    Layout = null;
}
<table class="table table-striped table-hover table-bordered" id="editable-sample">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Areas)
        {
            <tr class="">
                <td>@item.AreaId</td>
                <td>@item.Nome</td>
                <td><a class="editar-registro" href="javascript:EditarRegistro(@item.AreaId, '@ViewContext.RouteData.Values["Controller"]');"><img src="@Url.Content("~/Content/images/edit.png")" border="0" /></a></td>
                <td><a class="excluir-registro" href="javascript:ExcluirRegistro(@item.AreaId, '@ViewContext.RouteData.Values["Controller"]');"><img src="@Url.Content("~/Content/images/del.png")" border="0" /></a></td>
            </tr>
        }
    </tbody>
</table>