source/BancoConcursos/WebBConcursos/Controllers/InstituicoesController.cs
using Dominio;
using Infra.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBConcursos.Models;

namespace WebBConcursos.Controllers
{
    [Authorize]
    public class InstituicoesController : Controller
    {
        private readonly Repository repository;
        public InstituicoesController(Repository Repository)
        {
            this.repository = Repository;
        }
        public ActionResult Index()
        {
            return View(PreencheModel());
        }

        private InstituicaoViewModel PreencheModel()
        {
            int total = 0;
            IEnumerable<Instituicao> instituicoes = this.repository.InstituicaoRepository.GetMany(x => x.Desativado != true, x => x.Nome, 1000, 1, out total);
            return new InstituicaoViewModel(instituicoes);
        }

        public ActionResult Listar()
        {
            return PartialView("_listar", PreencheModel());
        }

        public ActionResult Excluir(int id)
        {
            Instituicao instituicao = this.repository.InstituicaoRepository.GetById(id);
            if (instituicao != null)
            {
                InstituicaoModel model = new InstituicaoModel(instituicao);
                return PartialView("_excluir", model);
            }
            return PartialView("_excluir", null);
        }

        [HttpPost]
        public ActionResult ExcluirFinal(int id)
        {
            if (ModelState.IsValid)
            {
                Instituicao instituicao = this.repository.InstituicaoRepository.GetById(id);
                if (instituicao != null)
                {
                    instituicao.Desativar();
                    this.repository.Save();
                }
                return View("_listar", PreencheModel());
            }
            else
            {
                return Json(new { Msg = "Preencha todos os campos!", Erro = true });
            }
        }

        public ActionResult Editar(int? id)
        {
            List<SelectListItem> listEstados = this.repository.EstadoRepository.GetAll().OrderBy(x => x.Nome).ToSelectList(t => t.Nome, x => x.EstadoId.ToString(), "Selecione", "");
            ViewBag.Estados = listEstados;
            ViewBag.Areas = this.repository.AreaRepository.GetAll().OrderBy(x => x.Nome).ToList().ToSelectList(x => x.Nome, y => y.AreaId.ToString(), "Selecione", "");
            List<SelectListItem> listCidades = MVCExtensoes.SelectListVazio();
            InstituicaoModel model = new InstituicaoModel();
            if (id.HasValue)
            {
                Instituicao instituicao = this.repository.InstituicaoRepository.GetById(id.Value);
                if (instituicao != null)
                {
                    if(instituicao.Estado != null)
                        listCidades = this.repository.CidadeRepository.GetMany(x => x.EstadoId == instituicao.EstadoId).ToSelectList(c => c.Nome, c => c.CidadeId.ToString(), "Selecione", "");
                    
                    model = new InstituicaoModel(instituicao);
                }
            }

            ViewBag.ListaDeCidades = listCidades;
            return PartialView("_editar", model);
        }

        [HttpPost]
        public ActionResult Editar(InstituicaoModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.InstituicaoId.HasValue)
                {
                    Instituicao instituicao = this.repository.InstituicaoRepository.GetById(model.InstituicaoId.Value);
                    if (instituicao != null)
                    {
                        instituicao.Alterar(model.Nome, model.Sigla, model.TextoDescritivo, model.Tags, model.AreaId, model.CidadeId, model.EstadoId, model.Url, model.Logradouro, model.Numero, model.Bairro);
                        this.repository.InstituicaoRepository.Update(instituicao);
                        this.repository.Save();
                    }
                }
                else
                {
                    Instituicao instituicao = new Instituicao(model.Nome, model.Sigla, model.TextoDescritivo, model.Tags, model.AreaId, model.CidadeId, model.EstadoId, model.Url, model.Logradouro, model.Numero, model.Bairro);
                    this.repository.InstituicaoRepository.Add(instituicao);
                    this.repository.Save();
                }

                return View("_listar", PreencheModel());
            }
            else
            {
                return Json(new { Msg = "Preencha todos os campos!", Erro = true });
            }
        }
	}
}

source/BancoConcursos/WebBConcursos/Views/Instituicoes/Index.cshtml
@{
    ViewBag.Title = "Admin - Instituições";
}

<div class="row">
    <div class="col-md-12">
        <h2>Instituições</h2>
    </div><!--/col-md-12-->
</div><!--/row-->

<div class="row">
    <div class="col-md-12">
        <div class="block-web">
            <div class="header">
                <div class="actions"> <a class="minimize" href="#"><i class="fa fa-chevron-down"></i></a> <a class="refresh" href="#"><i class="fa fa-repeat"></i></a> <a class="close-down" href="#"><i class="fa fa-times"></i></a> </div>
                <h3 class="content-header">&nbsp;</h3>
            </div>
            <div class="porlets-content">
                <div class="adv-table editable-table ">
                    <div class="clearfix">
                        <div class="btn-group">
                            <button class="btn btn-primary novo-registro" data-entity="@ViewContext.RouteData.Values["Controller"]">
                                Novo <i class="fa fa-plus"></i>
                            </button>
                        </div>
                        <div class="btn-group pull-right">
                            <button class="btn dropdown-toggle" data-toggle="dropdown">
                                Ferramentas <i class="fa fa-angle-down"></i>
                            </button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#">Imprimir</a></li>
                                <li><a href="#">Salvar como PDF</a></li>
                                <li><a href="#">Exportar par Excel</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="margin-top-10"></div>
                    <div id="div-listagem">
                        @Html.Action("Listar")
                    </div>
                </div>

            </div><!--/porlets-content-->
        </div><!--/block-web-->
    </div><!--/col-md-12-->
</div><!--/row-->

<div id="modal-result">
</div>

source/BancoConcursos/WebBConcursos/Views/Instituicoes/_editar.cshtml
@model WebBConcursos.Models.InstituicaoModel
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="modal-registro">
    @using (Ajax.BeginForm("Editar", "Instituicoes", new AjaxOptions { UpdateTargetId = "div-listagem", OnComplete = "Completo", OnFailure = "Falha", OnBegin = "Carregando", InsertionMode = InsertionMode.Replace }, new { @class = "form-horizontal", @style = "margin-bottom: 0px !important;" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(h => h.InstituicaoId)
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                    <h4 id="myModalLabel" class="modal-title">Editar Instituição</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true)
                        <div class="form-group w-v">
                            @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Nome, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Nome)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Sigla, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Sigla, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.TextoDescritivo, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.TextoDescritivo, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Tags, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Tags, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.AreaId, new { @class = "control-label col-md-2" })
                            <div class="col-md-10 w-v">
                                @Html.DropDownListFor(x => x.AreaId, (IEnumerable<SelectListItem>)ViewBag.Areas, new { @class = "campo-cadastro" })
                                @Html.ValidationMessageFor(model => model.AreaId)
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.EstadoId, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.DropDownListFor(x => x.EstadoId, (IEnumerable<SelectListItem>)ViewBag.Estados, new { @class = "campo-cadastro", @onchange = "getCidadesPorEstado($(this).val(), $('#CidadeId'))" })
                            </div>
                            @Html.LabelFor(model => model.CidadeId, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.DropDownListFor(x => x.CidadeId, (IEnumerable<SelectListItem>)ViewBag.ListaDeCidades, new { @class = "campo-cadastro" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Logradouro, new { @class = "control-label col-md-2" })
                            <div class="col-md-6">
                                @Html.TextBoxFor(model => model.Logradouro, new { @class = "form-control" })
                            </div>
                            @Html.LabelFor(model => model.Numero, new { @class = "control-label col-md-2" })
                            <div class="col-md-2">
                                @Html.TextBoxFor(model => model.Numero, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Bairro, new { @class = "control-label col-md-2" })
                            <div class="col-md-4">
                                @Html.TextBoxFor(model => model.Bairro, new { @class = "form-control" })
                            </div>
                            @Html.LabelFor(model => model.Url, new { @class = "control-label col-md-1" })
                            <div class="col-md-5">
                                @Html.TextBoxFor(model => model.Url, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cancelar</button>
                    <button class="btn btn-primary" type="submit">Salvar</button>
                </div>
            </div>
        </div>
    }
</div>
<script type="text/javascript">
    function ReparseValidation() {
        $.validator.unobtrusive.parse("#modal-registro");
    }
    ReparseValidation();
</script>

source/BancoConcursos/WebBConcursos/Views/Instituicoes/_excluir.cshtml
@model WebBConcursos.Models.InstituicaoModel
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="modal-delete">
    @using (Ajax.BeginForm("ExcluirFinal", "Instituicoes", new AjaxOptions { UpdateTargetId = "div-listagem", OnComplete = "Completo", OnFailure = "Falha", OnBegin = "Carregando", InsertionMode = InsertionMode.Replace }, new { @class = "form-horizontal", @style = "margin-bottom: 0px !important;" }))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" id="id" value="@Model.InstituicaoId" />
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                    <h4 id="myModalLabel" class="modal-title">Excluir Instituição</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        Deseja realmente excluir o registro abaixo?
                        <div class="form-group">
                            <div class="col-md-12">
                                @Html.DisplayTextFor(model => model.Nome)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default" type="button">Cancelar</button>
                    <button class="btn btn-danger" type="submit">Excluir</button>
                </div>
            </div>
        </div>
    }
</div>

source/BancoConcursos/WebBConcursos/Views/Instituicoes/_listar.cshtml
@model WebBConcursos.Models.InstituicaoViewModel
@{
    Layout = null;
}
<table class="table table-striped table-hover table-bordered" id="editable-sample">
    <thead>
        <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>Sigla</th>
            <th>Cadastro</th>
            <th>Alteração</th>
            <th>Editar</th>
            <th>Excluir</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Instituicoes)
        {
            <tr class="">
                <td>@item.InstituicaoId</td>
                <td>@item.Nome</td>
                <td>@item.Sigla</td>
                <td>@item.DataCadastro</td>
                <td>@item.DataAlteracao</td>
                <td><a class="editar-registro" href="javascript:EditarRegistro(@item.InstituicaoId, '@ViewContext.RouteData.Values["Controller"]');"><img src="@Url.Content("~/Content/images/edit.png")" border="0" /></a></td>
                <td><a class="excluir-registro" href="javascript:ExcluirRegistro(@item.InstituicaoId, '@ViewContext.RouteData.Values["Controller"]');"><img src="@Url.Content("~/Content/images/del.png")" border="0" /></a></td>
            </tr>
        }
    </tbody>
</table>